DROP TABLE IF EXISTS Teams;
CREATE TABLE IF NOT EXISTS Teams (teamNumber TEXT PRIMARY KEY, teamNumber INTEGER KEY, nickname TEXT);

DROP TABLE IF EXISTS Events;
CREATE TABLE IF NOT EXISTS Events (eventKey TEXT PRIMARY KEY, eventName TEXT, startTime INTEGER);

