-- Migration number: 0002 	 2024-02-05T01:35:20.772Z
DELETE FROM Matches;

INSERT INTO 
  Matches (matchKey, startTime, eventKey, reportedWinningAlliance, reportedRedScore, reportedBlueScore)
VALUES
  ("2024mock_qm1", 1707541200720, "2024mock", "red", 120, 80),
  ("2024mock_qm2", 1707541200780, "2024mock", "blue", 60, 80),
  ("2024mock_qm3", 1707541200840, "2024mock", "red", 100, 80);

DELETE FROM TeamMatchEntry;
INSERT INTO TeamMatchEntry (matchKey, teamNumber, alliance, matchData)
VALUES 
  ("2024mock_qm1", 9991, "red", " { ""scoutname"": ""Kennan"",  ""position"": ""Red1"",  ""matchnumber"": 1, ""teamnumber"": 9991, ""noshow"": false, ""startingpos"": 1,    ""1"": false, ""2"": false, ""3"": true,  ""4"": false, ""5"": false, ""6"": false, ""7"": false, ""8"": true,  ""autoamp"": 2,    ""autospeaker"": 0,    ""leave"": true,  ""teleopamp"": 8,    ""teleopspeaker"": 0,     ""subwoofer"": false, ""podium"": false, ""wing"": false, ""outside"": false, ""teleoptrap"": 1,    ""climbtime"": 15,   ""onstage"": 1,     ""amplifications"": 1, ""harmonize"": null, ""buddy"": false, ""spotlit"": 0,    ""floor"": 1,    ""source"": 1,    ""understage"": true,  ""playeddefense"": false, ""receiveddefense"": false, ""died"": false, ""tipped"": false, ""broke"": false, ""rating"": 2,    ""comments"": ""good amp bot"" }"),
  ("2024mock_qm1", 9992, "red", " { ""scoutname"": ""Mady"",    ""position"": ""Red2"",  ""matchnumber"": 1, ""teamnumber"": 9992, ""noshow"": true,  ""startingpos"": null, ""1"": null,  ""2"": null,  ""3"": null,  ""4"": null,  ""5"": null,  ""6"": null,  ""7"": null,  ""8"": null,  ""autoamp"": null, ""autospeaker"": null, ""leave"": null,  ""teleopamp"": null, ""teleopspeaker"": null,  ""subwoofer"": null,  ""podium"": null,  ""wing"": null,  ""outside"": null,  ""teleoptrap"": null, ""climbtime"": null, ""onstage"": null,  ""amplifications"": 1, ""harmonize"": null, ""buddy"": null,  ""spotlit"": null, ""floor"": null, ""source"": null, ""understage"": null,  ""playeddefense"": null,  ""receiveddefense"": null,  ""died"": null,  ""tipped"": null,  ""broke"": null,  ""rating"": null, ""comments"": """" }"),
  ("2024mock_qm1", 9993, "red", " { ""scoutname"": ""Jiping"",  ""position"": ""Red3"",  ""matchnumber"": 1, ""teamnumber"": 9993, ""noshow"": false, ""startingpos"": 2,    ""1"": true,  ""2"": false, ""3"": false, ""4"": false, ""5"": false, ""6"": false, ""7"": false, ""8"": false, ""autoamp"": 0,    ""autospeaker"": 2,    ""leave"": true,  ""teleopamp"": 1,    ""teleopspeaker"": 6,     ""subwoofer"": true,  ""podium"": false, ""wing"": false, ""outside"": false, ""teleoptrap"": 0,    ""climbtime"": 5,    ""onstage"": 0,     ""amplifications"": 1, ""harmonize"": 1,    ""buddy"": false, ""spotlit"": 1,    ""floor"": 0,    ""source"": 1,    ""understage"": false, ""playeddefense"": false, ""receiveddefense"": false, ""died"": true,  ""tipped"": false, ""broke"": false, ""rating"": 3,    ""comments"": ""meh speaker bot"" }"),
  ("2024mock_qm1", 9994, "blue", "{ ""scoutname"": ""Pam"",     ""position"": ""Blue1"", ""matchnumber"": 1, ""teamnumber"": 9994, ""noshow"": false, ""startingpos"": 3,    ""1"": false, ""2"": true,  ""3"": false, ""4"": false, ""5"": false, ""6"": true,  ""7"": false, ""8"": false, ""autoamp"": 0,    ""autospeaker"": 1,    ""leave"": true,  ""teleopamp"": 4,    ""teleopspeaker"": 3,     ""subwoofer"": false, ""podium"": true,  ""wing"": false, ""outside"": false, ""teleoptrap"": 0,    ""climbtime"": null, ""onstage"": 0,     ""amplifications"": 1, ""harmonize"": null, ""buddy"": false, ""spotlit"": 0,    ""floor"": 1,    ""source"": 0,    ""understage"": false, ""playeddefense"": false, ""receiveddefense"": true,  ""died"": false, ""tipped"": false, ""broke"": true,  ""rating"": 1,    ""comments"": ""impressive can switch between speaker and amp"" }"),
  ("2024mock_qm1", 9995, "blue", "{ ""scoutname"": ""Scott"",   ""position"": ""Blue2"", ""matchnumber"": 1, ""teamnumber"": 9995, ""noshow"": false, ""startingpos"": 4,    ""1"": false, ""2"": false, ""3"": false, ""4"": false, ""5"": false, ""6"": false, ""7"": false, ""8"": false, ""autoamp"": 0,    ""autospeaker"": 0,    ""leave"": false, ""teleopamp"": 5,    ""teleopspeaker"": 0,     ""subwoofer"": false, ""podium"": false, ""wing"": false, ""outside"": false, ""teleoptrap"": 0,    ""climbtime"": 20,   ""onstage"": 1,     ""amplifications"": 1, ""harmonize"": 1,    ""buddy"": false, ""spotlit"": 0,    ""floor"": 0,    ""source"": 1,    ""understage"": true,  ""playeddefense"": false, ""receiveddefense"": false, ""died"": false, ""tipped"": false, ""broke"": false, ""rating"": 3,    ""comments"": """" }"), 
  ("2024mock_qm1", 9996, "blue", "{ ""scoutname"": ""Abbey"",   ""position"": ""Blue3"", ""matchnumber"": 1, ""teamnumber"": 9996, ""noshow"": false, ""startingpos"": 1,    ""1"": true,  ""2"": true,  ""3"": true,  ""4"": false, ""5"": false, ""6"": false, ""7"": false, ""8"": false, ""autoamp"": 0,    ""autospeaker"": 4,    ""leave"": true,  ""teleopamp"": 0,    ""teleopspeaker"": 9,     ""subwoofer"": false, ""podium"": false, ""wing"": true,  ""outside"": false, ""teleoptrap"": 0,    ""climbtime"": 10,   ""onstage"": 1,     ""amplifications"": 1, ""harmonize"": null, ""buddy"": false, ""spotlit"": 0,    ""floor"": 1,    ""source"": 0,    ""understage"": false, ""playeddefense"": false, ""receiveddefense"": true,  ""died"": false, ""tipped"": true,  ""broke"": false, ""rating"": 1,    ""comments"": ""super fast cycles;"" }"),
  -- match 2
  ("2024mock_qm2", 9998, "red", " { ""scoutname"": ""Jessica"", ""position"": ""Red1"",  ""matchnumber"": 2, ""teamnumber"": 9998, ""noshow"": false, ""startingpos"": 2,    ""1"": false, ""2"": false, ""3"": false, ""4"": true,  ""5"": false, ""6"": false, ""7"": false, ""8"": false, ""autoamp"": 1,    ""autospeaker"": 1,    ""leave"": true,  ""teleopamp"": 2,    ""teleopspeaker"": 5,     ""subwoofer"": false, ""podium"": false, ""wing"": true,  ""outside"": true,  ""teleoptrap"": 2,    ""climbtime"": 10,   ""onstage"": 1,     ""amplifications"": 1, ""harmonize"": null, ""buddy"": false, ""spotlit"": 0,    ""floor"": 1,    ""source"": 1,    ""understage"": true,  ""playeddefense"": false, ""receiveddefense"": false, ""died"": false, ""tipped"": false, ""broke"": false, ""rating"": 2,    ""comments"": ""good all around bot"" }"),
  ("2024mock_qm2", 9997, "red", " { ""scoutname"": ""Ezrah"",   ""position"": ""Red2"",  ""matchnumber"": 2, ""teamnumber"": 9997, ""noshow"": false, ""startingpos"": 3,    ""1"": false, ""2"": false, ""3"": true,  ""4"": false, ""5"": false, ""6"": false, ""7"": false, ""8"": false, ""autoamp"": 0,    ""autospeaker"": 1,    ""leave"": true,  ""teleopamp"": 0,    ""teleopspeaker"": 6,     ""subwoofer"": false, ""podium"": false, ""wing"": true,  ""outside"": false, ""teleoptrap"": 1,    ""climbtime"": 42,   ""onstage"": 1,     ""amplifications"": 1, ""harmonize"": 2,    ""buddy"": true,  ""spotlit"": 3,    ""floor"": 0,    ""source"": 1,    ""understage"": true,  ""playeddefense"": true,  ""receiveddefense"": false, ""died"": false, ""tipped"": false, ""broke"": false, ""rating"": 3,    ""comments"": ""used the a stop"" }"),
  ("2024mock_qm2", 9996, "red", " { ""scoutname"": ""Ross"",    ""position"": ""Red3"",  ""matchnumber"": 2, ""teamnumber"": 9996, ""noshow"": false, ""startingpos"": 4,    ""1"": false, ""2"": false, ""3"": true,  ""4"": false, ""5"": false, ""6"": false, ""7"": false, ""8"": false, ""autoamp"": 0,    ""autospeaker"": 1,    ""leave"": true,  ""teleopamp"": 0,    ""teleopspeaker"": 10,    ""subwoofer"": false, ""podium"": false, ""wing"": false, ""outside"": true,  ""teleoptrap"": 0,    ""climbtime"": null, ""onstage"": 0,     ""amplifications"": 1, ""harmonize"": null, ""buddy"": false, ""spotlit"": 0,    ""floor"": 1,    ""source"": 0,    ""understage"": false, ""playeddefense"": false, ""receiveddefense"": false, ""died"": false, ""tipped"": false, ""broke"": false, ""rating"": 1,    ""comments"": """" }"),
  ("2024mock_qm2", 9995, "blue", "{ ""scoutname"": ""Ava"",     ""position"": ""Blue1"", ""matchnumber"": 2, ""teamnumber"": 9995, ""noshow"": false, ""startingpos"": 1,    ""1"": false, ""2"": false, ""3"": false, ""4"": false, ""5"": false, ""6"": false, ""7"": false, ""8"": false, ""autoamp"": 0,    ""autospeaker"": 1,    ""leave"": false, ""teleopamp"": 0,    ""teleopspeaker"": 2,     ""subwoofer"": true,  ""podium"": false, ""wing"": false, ""outside"": false, ""teleoptrap"": 0,    ""climbtime"": 8,    ""onstage"": 1,     ""amplifications"": 1, ""harmonize"": null, ""buddy"": false, ""spotlit"": 0,    ""floor"": 0,    ""source"": 1,    ""understage"": false, ""playeddefense"": false, ""receiveddefense"": false, ""died"": false, ""tipped"": false, ""broke"": false, ""rating"": 3,    ""comments"": ""terrible driving, got penalties"" }"),
  ("2024mock_qm2", 9994, "blue", "{ ""scoutname"": ""Carter"",  ""position"": ""Blue2"", ""matchnumber"": 2, ""teamnumber"": 9994, ""noshow"": false, ""startingpos"": 2,    ""1"": false, ""2"": true,  ""3"": false, ""4"": false, ""5"": true,  ""6"": false, ""7"": false, ""8"": false, ""autoamp"": 3,    ""autospeaker"": 0,    ""leave"": true,  ""teleopamp"": 3,    ""teleopspeaker"": 0,     ""subwoofer"": false, ""podium"": false, ""wing"": false, ""outside"": false, ""teleoptrap"": 3,    ""climbtime"": 3,    ""onstage"": 2,     ""amplifications"": 1, ""harmonize"": 1,    ""buddy"": false, ""spotlit"": 1,    ""floor"": 1,    ""source"": 0,    ""understage"": false, ""playeddefense"": true,  ""receiveddefense"": false, ""died"": false, ""tipped"": false, ""broke"": false, ""rating"": 2,    ""comments"": ""great harmonize at the last second"" }"),
  ("2024mock_qm2", 9993, "blue", "{ ""scoutname"": ""Landon"",  ""position"": ""Blue3"", ""matchnumber"": 2, ""teamnumber"": 9993, ""noshow"": false, ""startingpos"": 3,    ""1"": false, ""2"": false, ""3"": true,  ""4"": false, ""5"": false, ""6"": false, ""7"": false, ""8"": false, ""autoamp"": 0,    ""autospeaker"": 1,    ""leave"": true,  ""teleopamp"": 0,    ""teleopspeaker"": 8,     ""subwoofer"": true,  ""podium"": false, ""wing"": false, ""outside"": false, ""teleoptrap"": 0,    ""climbtime"": 21,   ""onstage"": 3,     ""amplifications"": 1, ""harmonize"": 2,    ""buddy"": false, ""spotlit"": 0,    ""floor"": 1,    ""source"": 1,    ""understage"": true,  ""playeddefense"": false, ""receiveddefense"": false, ""died"": false, ""tipped"": false, ""broke"": false, ""rating"": 1,    ""comments"": """" }"),
  -- match 3
  ("2024mock_qm3", 9996, "red", " { ""scoutname"": ""Traevor"", ""position"": ""Red1"",  ""matchnumber"": 3, ""teamnumber"": 9996, ""noshow"": false, ""startingpos"": 4,    ""1"": false, ""2"": false, ""3"": false, ""4"": false, ""5"": false, ""6"": false, ""7"": false, ""8"": false, ""autoamp"": 0,    ""autospeaker"": 0,    ""leave"": false, ""teleopamp"": 0,    ""teleopspeaker"": 4,     ""subwoofer"": true,  ""podium"": false, ""wing"": false, ""outside"": false, ""teleoptrap"": 0,    ""climbtime"": 17,   ""onstage"": 1,     ""amplifications"": 1, ""harmonize"": null, ""buddy"": false, ""spotlit"": 0,    ""floor"": 0,    ""source"": 1,    ""understage"": true,  ""playeddefense"": false, ""receiveddefense"": false, ""died"": false, ""tipped"": false, ""broke"": false, ""rating"": 2,    ""comments"": """" }");