import { z } from "zod";

export const matchDataSchema = z.object({
  "1": z.boolean().nullable(),
  "2": z.boolean().nullable(),
  "3": z.boolean().nullable(),
  "4": z.boolean().nullable(),
  "5": z.boolean().nullable(),
  "6": z.boolean().nullable(),
  "7": z.boolean().nullable(),
  "8": z.boolean().nullable(),
  amplifications: z.number().nullable(),
  autoamp: z.number().nullable(),
  autospeaker: z.number().nullable(),
  broke: z.boolean().nullable(),
  buddy: z.boolean().nullable(),
  climbtime: z.number().nullable(),
  comments: z.string().nullable(),
  died: z.boolean().nullable(),
  floor: z.number().nullable(),
  harmonize: z.number().nullable(),
  leave: z.boolean().nullable(),
  matchnumber: z.number().nullable(),
  noshow: z.boolean().nullable(),
  onstage: z.number().nullable(),
  outside: z.boolean().nullable(),
  playeddefense: z.boolean().nullable(),
  podium: z.boolean().nullable(),
  position: z.string().nullable(),
  rating: z.number().nullable(),
  receiveddefense: z.boolean().nullable(),
  scoutname: z.string().nullable(),
  source: z.number().nullable(),
  spotlit: z.number().nullable(),
  startingpos: z.number().nullable(),
  subwoofer: z.boolean().nullable(),
  teamnumber: z.number().nullable(),
  teleopamp: z.number().nullable(),
  teleopspeaker: z.number().nullable(),
  teleoptrap: z.number().nullable(),
  tipped: z.boolean().nullable(),
  understage: z.boolean().nullable(),
  wing: z.boolean().nullable(),
});
