import { z } from "zod";

export const TBAEventSchema = z.object({
  address: z.string(),
  city: z.string(),
  country: z.string(),
  district: z.unknown(),
  division_keys: z.string().array(),
  end_date: z.string(),
  event_code: z.string(),
  event_type_string: z.string(),
  event_type: z.number(),
  first_event_code: z.string(),
  first_event_id: z.null(),
  gmaps_place_id: z.string(),
  gmaps_url: z.string(),
  key: z.string(),
  lat: z.number(),
  lng: z.number(),
  location_name: z.string(),
  name: z.string(),
  parent_event_key: z.string().nullable(),
  playoff_type_string: z.string(),
  playoff_type: z.number(),
  postal_code: z.string(),
  short_name: z.string(),
  start_date: z.string(),
  state_prov: z.string(),
  timezone: z.string(),
  webcasts: z.object({ channel: z.string(), type: z.string() }).array(),
  website: z.string(),
  week: z.number().nullable(),
  year: z.number(),
});
