name = "scouting-api"
main = "src/index.ts"
minify = true
compatibility_date = "2023-01-01"
account_id = "1de9d7646d10b16be16d4afc4ac9a19b"

[vars]
# needs
# - JWT_SECRET
# - TBA_KEY

[[d1_databases]]
binding = "DB"
database_name = "scouting-db"
database_id = "d95b989c-6cfd-4070-a0a5-7ce45bc6f3a2"
